version: '3' # vs mais atual
networks:
  nlw-network:
    driver: bridge
services:             

  app:
    build: nodejs
    container_name: nlw-06-nodejs
    restart: always
    tty: true
    networks:
      - nlw-network
    ports:
      - "3000:3000"
    volumes:       
      - ./nodejs:/src/app
    working_dir: /src/app
    environment:
      - PORT=3000
      # ESCOLHA O SEU DRIVE ENTRE sqlite, mysql E postgres 
      - CONNECTION_DRIVE=sqlite
      # CONFIGURAÇÕES MIGRATIONS
      - TYPE_ORM_LOGGING=true     
      - TYPE_ORM_MIGRATIONS=./src/database/migrations/**.ts
      - TYPE_ORM_MIGRATIONS_DIR=./src/database/migrations
      # PARA OS DRIVE ENTRE sqlite, mysql E postgres
      - TYPE_ORM_ENTITIES=./src/entities
      - TYPE_ORM_ENTITIES_DIR=./src/entities/**.ts
    depends_on: 
      - db_mysql
      - db_pg

  # CONFIGURAÇÕES MYSQL
  db_mysql:
    container_name: db_mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3336:3306"
    volumes:
      - ./dbs/mysql/dbdata:/var/lib/mysql
      - ./dbs/init/nlw_mysql.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_DATABASE=database_nlw
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nlw-network
  
  # CONFIGURAÇÕES POSTGRES
  db_pg:
    container_name: db_pg
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - ./dbs/init/nlw_pg.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbs/pg/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database_nlw
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5432
    networks:
      - nlw-network